In [3]:
import pandas as pd

In [4]:
path=r"C:\Users\chait\OneDrive\Documents\Generative-Ai\Generative-AI\Gen-AI\IMDB Dataset.csv"
df=pd.read_csv(path)


In [5]:
df.head(100)

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
...,...,...
95,Daniel Day-Lewis is the most versatile actor a...,positive
96,My guess would be this was originally going to...,negative
97,"Well, I like to watch bad horror B-Movies, cau...",negative
98,"This IS the worst movie I have ever seen, as w...",negative


In [6]:
df.shape

(50000, 2)

In [7]:
df=df.head(100)

In [8]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [9]:
df['review']=df['review'].str.lower()

df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [10]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. <br /><br />the...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive


In [11]:
#removal of html tags
import re
def remove_html_tags(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)


In [12]:
text="<p>This is a <b>sample</b> text after removing <a href='#'>HTML tags</a>.</p>"
cleaned_text = remove_html_tags(text)
cleaned_text

'This is a sample text after removing HTML tags.'

In [13]:
df['review']=df['review'].apply(remove_html_tags)

In [14]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return re.sub(pattern,'',text)

In [15]:
text="this is my linked in profile https://www.linkedin.com/in/chaitanyasai07/"
cleaned_text = remove_url(text)
cleaned_text

'this is my linked in profile '

In [16]:
#removed urls from the reviews
df['review'] = df['review'].apply(remove_url)

In [17]:
import string,time
exclude=string.punctuation

In [18]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', exclude))

In [19]:
text="this, is , a sample. text with removed! punctuation"
start=time.time()
cleaned_text = remove_punctuation(text)
end=time.time()-start
print(f"Time taken to remove punctuation: {end*50000} seconds")
cleaned_text

Time taken to remove punctuation: 0.0 seconds


'this is  a sample text with removed punctuation'

In [20]:
df['review']=df['review'].apply(remove_punctuation)
df['review'][8]

'encouraged by the positive comments about this film on here i was looking forward to watching this film bad mistake ive seen 950 films and this is truly one of the worst of them  its awful in almost every way editing pacing storyline acting soundtrack the films only song  a lame country tune  is played no less than four times the film looks cheap and nasty and is boring in the extreme rarely have i been so happy to see the end credits of a film the only thing that prevents me giving this a 1score is harvey keitel  while this is far from his best performance he at least seems to be making a bit of an effort one for keitel obsessives only'

In [21]:
chat_words={
    "u": "you",
    "r": "are",
    "4": "for", 
    "ur": "your",
    "afk": "away from keyboard",
    "brb": "be right back",
    "btw": "by the way",
    "imo": "in my opinion",
    "idk": "I don't know",
    "lmao": "laughing my ass off",
    "afaik":"as far as i know",
    "ikr":"i know right",
    "faq":"frequently asked question",
    "fyi":"for your information"
}

In [22]:
def chat_convertion(text):
    new_text=[]
    for w in text.split():
        if(w.lower() in chat_words):
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)

    return " ".join(new_text)

In [23]:
chat_convertion('btw , u r going to do this 4 ur project')

'by the way , you are going to do this for your project'

In [25]:
from textblob import TextBlob

In [26]:
#to correct spelling mistakes
from textblob import TextBlob

incorrect_text = "the spallings of thuis santance is changus after usjng textbolbb"
blob = TextBlob(incorrect_text)

# Option 1: just print the corrected TextBlob
print(blob.correct())

# Option 2: get a plain string
corrected = str(blob.correct())


the swellings of this sentence is changes after using textbolbb


In [27]:
#stopwords removal
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [28]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [29]:
len(stopwords.words('english'))

198

In [30]:
def remove_stopwords(text):
    newtext=[]
    for word in text.split():
        if word in stopwords.words('english'):
            newtext.append('')
        else:
            newtext.append(word)
    x=newtext[:]
    newtext.clear()
    return " ".join(x)

In [31]:
remove_stopwords('this is a sample text with some stopwords like the and is')

'   sample text   stopwords like   '

In [32]:
df['review']=df['review'].apply(remove_stopwords)

In [33]:
df.head(20)

,review,sentiment
0,one reviewers mentioned watching 1 oz e...,positive
1,wonderful little production filming techniqu...,positive
2,thought wonderful way spend time hot s...,positive
3,basically theres family little boy jake thi...,negative
4,petter matteis love time money visually s...,positive
5,probably alltime favorite movie story selfl...,positive
6,sure would like see resurrection dated s...,positive
7,show amazing fresh innovative idea 70s ...,negative
8,encouraged positive comments film look...,negative
9,like original gut wrenching laughter like ...,positive


In [34]:
#emojis removal
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "\U00002702-\U000027B0"  # dingbats
        "\U000024C2-\U0001F251"  # enclosed characters
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r'', text)

In [35]:
remove_emojis('This is a sample text with emojis 😊🚀 and some more text.')

'This is a sample text with emojis  and some more text.'

In [36]:
remove_emojis("lol 😂😂😂")

'lol '

In [37]:
df['review']=df['review'].apply(remove_emojis)

In [40]:
import emoji
print(emoji.demojize('😂'))
emoji.demojize('the movie of 🔥')

:face_with_tears_of_joy:


'the movie of :fire:'

In [41]:
#tokenization
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [42]:
sent="hello, how are you?"
tokens=word_tokenize(sent)
print(tokens)

['hello', ',', 'how', 'are', 'you', '?']


In [43]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


Word                Lemma               
He                  He                  
was                 be                  
running             run                 
and                 and                 
eating              eat                 
at                  at                  
same                same                
time                time                
He                  He                  
has                 have                
bad                 bad                 
habit               habit               
of                  of                  
swimming            swim                
after               after               
playing             play                
long                long                
hours               hours               
in                  in                  
the                 the                 
Sun                 Sun                 


In [44]:
#Feature Extraction
df=pd.DataFrame({'text':["I am running","He was running","They are playing","She is swimming"],'output':[0,1,0,1]})

In [45]:
df

,text,output
0,I am running,0
1,He was running,1
2,They are playing,0
3,She is swimming,1


In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [47]:
bow=cv.fit_transform(df['text'])

In [48]:
print(cv.vocabulary_)

{'am': 0, 'running': 5, 'he': 2, 'was': 9, 'they': 8, 'are': 1, 'playing': 4, 'she': 6, 'is': 3, 'swimming': 7}


In [49]:
bow.toarray()

array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0]], dtype=int64)

In [50]:
print(bow[0].toarray())

[[1 0 0 0 0 1 0 0 0 0]]


In [51]:
cv.transform(['she is running']).toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [52]:
X=bow.toarray()
y=df['output']

In [53]:
#N-grams
cv=CountVectorizer(ngram_range=(2,2))

In [54]:
bow=cv.fit_transform(df['text'])

In [55]:
print(cv.vocabulary_)

{'am running': 0, 'he was': 2, 'was running': 6, 'they are': 5, 'are playing': 1, 'she is': 4, 'is swimming': 3}


In [56]:
bow[0].toarray()

array([[1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [57]:
cv.transform(['they are swimming']).toarray()

array([[0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [58]:
#above we considered two-grams(words) so it is called are bigrams same way we can form trigrams, four-grams etc.


In [59]:
#TF-IDF term frequency-inverse document frequency
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [60]:
arr=tfidf.fit_transform(df['text'])

In [61]:
arr.toarray()

array([[0.78528828, 0.        , 0.        , 0.        , 0.        ,
        0.6191303 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.61761437, 0.        , 0.        ,
        0.48693426, 0.        , 0.        , 0.        , 0.61761437],
       [0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.57735027, 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027, 0.57735027, 0.        , 0.        ]])

In [62]:
print(arr.toarray())

[[0.78528828 0.         0.         0.         0.         0.6191303
  0.         0.         0.         0.        ]
 [0.         0.         0.61761437 0.         0.         0.48693426
  0.         0.         0.         0.61761437]
 [0.         0.57735027 0.         0.         0.57735027 0.
  0.         0.         0.57735027 0.        ]
 [0.         0.         0.         0.57735027 0.         0.
  0.57735027 0.57735027 0.         0.        ]]


In [63]:
import gensim
import os
import pandas as pd
import numpy as np

In [64]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chait\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [65]:
data=r"C:\Users\chait\OneDrive\Documents\Generative-Ai\Generative-AI\Gen-AI\gameofthrones.txt"

In [66]:
story = []

# Read the file
with open(data, "r", encoding="utf-8") as f:
    corpus = f.read()

# Sentence tokenization
raw_sentences = sent_tokenize(corpus)

# Preprocess each sentence
for sent in raw_sentences:
    story.append(simple_preprocess(sent))

In [67]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chap

In [68]:
story[0]

['storm',
 'of',
 'swords',
 'book',
 'three',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george']

In [86]:
import gensim
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [70]:
model.build_vocab(story)

In [71]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1542339, 2049890)

In [72]:
model.wv.most_similar('daenerys')

[('mag', 0.9896919131278992),
 ('doom', 0.989369809627533),
 ('khal', 0.9884417057037354),
 ('eyed', 0.987953245639801),
 ('outlaw', 0.9877286553382874),
 ('tyroshi', 0.9870201349258423),
 ('raider', 0.9868928790092468),
 ('singer', 0.9868418574333191),
 ('numbers', 0.9866340160369873),
 ('collio', 0.986312210559845)]

In [73]:
model.wv.similarity('arya','sansa')

0.8560227

In [74]:
model.wv.get_normed_vectors().shape

(9475, 100)

In [75]:
y = model.wv.index_to_key

In [76]:
len(y)

9475

In [77]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'you',
 'was',
 'it',
 'in',
 'her',
 'that',
 'had',
 'she',
 'as',
 'but',
 'him',
 'with',
 'for',
 'not',
 'they',
 'said',
 'at',
 'on',
 'my',
 'have',
 'be',
 'is',
 'lord',
 'no',
 'them',
 'me',
 'all',
 'were',
 'from',
 'your',
 'would',
 'so',
 'when',
 'one',
 'ser',
 'if',
 'we',
 'could',
 'there',
 'will',
 'their',
 'are',
 'up',
 'did',
 'man',
 'king',
 'this',
 'or',
 'well',
 'back',
 'what',
 'more',
 'been',
 'by',
 'do',
 'down',
 'out',
 'jon',
 'who',
 'than',
 'page',
 'like',
 'only',
 'men',
 'now',
 'too',
 'father',
 'know',
 'before',
 'even',
 'never',
 'then',
 'old',
 'hand',
 'off',
 'tyrion',
 'see',
 'some',
 'made',
 'lady',
 'thought',
 'an',
 'll',
 'how',
 'into',
 'black',
 'jaime',
 'might',
 'told',
 'can',
 'time',
 'through',
 'long',
 'head',
 'come',
 'eyes',
 'still',
 'good',
 'sansa',
 'us',
 'once',
 'though',
 'arya',
 'red',
 'here',
 'took',
 'face',
 'where',
 'two',
 'say',
 'little'

In [78]:
from sklearn.decomposition import PCA

In [79]:
pca = PCA(n_components=3)

In [80]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [81]:
X

array([[ 0.41378292, -0.16867474, -0.44191316],
       [ 0.46382937, -0.07308131, -0.22985356],
       [-0.4444824 , -0.32003194,  0.11361028],
       ...,
       [ 0.01541914, -0.01803893,  0.07027628],
       [-0.09305401, -0.15789518, -0.10172106],
       [ 0.29700777,  0.06305301,  0.06839247]], dtype=float32)

In [82]:
X.shape

(9475, 3)

In [85]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()